Add optional second argument for $machtype, if no /proc/hardware is available. Make display relevant commands, just like make. Also install lilo/atari/bootos.

diff --git a/do_install b/do_install
--- a/do_install
+++ b/do_install
@@ -1,28 +1,37 @@
 #!/bin/sh
 set -e
 
-if [ $# -ne 1 ]; then
-	echo "Usage: $0 destination-prefix" 1>&2
+if [ $# -lt 1 -o $# -gt 2 ]; then
+	echo "Usage: $0 destination-prefix [machine-type]" 1>&2
 	exit 1
 fi
 PREFIX="$1"
 
-# get machine type
-machtype=`awk '/^Model:/ {print $2}' /proc/hardware | tr A-Z a-z`
-if [ -z "$machtype" ]; then
-	echo "Could not determine machine type!" 1>&2
-	exit 1
-fi
-if [ "$machtype" -ne "atari" -a "$machtype" -ne "amiga" ]; then
-	echo "Unsupported machine type: $machtype" 1>&2
-	exit 1
+if [ $# -eq 2 ]; then
+	machtype="$2"
+else
+	# get machine type
+	machtype=`awk '/^Model:/ {print $2}' /proc/hardware | tr A-Z a-z`
+	if [ -z "$machtype" ]; then
+		echo "Could not determine machine type!" 1>&2
+		exit 1
+	fi
+	if [ "$machtype" -ne "atari" -a "$machtype" -ne "amiga" ]; then
+		echo "Unsupported machine type: $machtype" 1>&2
+		exit 1
+	fi
 fi
 
+set -v
 install -m755 lilo/$machtype/lilo $PREFIX/sbin/lilo
 install -m644 lilo/$machtype/loader $PREFIX/boot/loader
 if [ ! -f $PREFIX/etc/lilo.conf ]; then
 	install -m644 lilo/$machtype/lilo.conf.example $PREFIX/etc/lilo.conf
 	echo "You have to edit /etc/lilo.conf"
 fi
+if [ "$machtype" = atari ]; then
+	install -m755 lilo/atari/bootos $PREFIX/sbin/bootos
+fi
+set +v
 
 exit 0
